from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 140)
        self.testCard_4 = QtWidgets.QWidget(Form)
        self.testCard_4.setGeometry(QtCore.QRect(0, 0, 300, 140))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testCard_4.sizePolicy().hasHeightForWidth())
        self.testCard_4.setSizePolicy(sizePolicy)
        self.testCard_4.setMinimumSize(QtCore.QSize(300, 140))
        self.testCard_4.setMaximumSize(QtCore.QSize(300, 140))
        self.testCard_4.setStyleSheet("background-color: rgb(64, 128, 2);\n"
"border-radius: 10px;")
        self.testCard_4.setObjectName("testCard_4")
        self.submitButton_4 = QtWidgets.QPushButton(self.testCard_4)
        #self.submitButton_4.setEnabled(False)
        self.submitButton_4.setGeometry(QtCore.QRect(190, 54, 96, 32))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        self.submitButton_4.setFont(font)
        self.submitButton_4.setAcceptDrops(False)
        self.submitButton_4.setStyleSheet("QPushButton{\n"
"background-color: gray;}\n")
        self.submitButton_4.setAutoDefault(False)
        self.submitButton_4.setDefault(False)
        self.submitButton_4.setFlat(False)
        self.submitButton_4.setObjectName("submitButton_4")
        self.cardInfo_4 = QtWidgets.QWidget(self.testCard_4)
        self.cardInfo_4.setGeometry(QtCore.QRect(0, 10, 181, 120))
        self.cardInfo_4.setStyleSheet("color:white;")
        self.cardInfo_4.setObjectName("cardInfo_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.cardInfo_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ClassName_4 = QtWidgets.QLabel(self.cardInfo_4)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(18)
        self.ClassName_4.setFont(font)
        self.ClassName_4.setAutoFillBackground(False)
        self.ClassName_4.setAlignment(QtCore.Qt.AlignCenter)
        self.ClassName_4.setWordWrap(False)
        self.ClassName_4.setObjectName("ClassName_4")
        self.verticalLayout_4.addWidget(self.ClassName_4)
        self.className_4 = QtWidgets.QLabel(self.cardInfo_4)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        self.className_4.setFont(font)
        self.className_4.setAlignment(QtCore.Qt.AlignCenter)
        self.className_4.setObjectName("className_4")
        self.verticalLayout_4.addWidget(self.className_4)
        self.DeadLine_4 = QtWidgets.QLabel(self.cardInfo_4)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(18)
        self.DeadLine_4.setFont(font)
        self.DeadLine_4.setAlignment(QtCore.Qt.AlignCenter)
        self.DeadLine_4.setObjectName("DeadLine_4")
        self.verticalLayout_4.addWidget(self.DeadLine_4)
        self.deadLine_4 = QtWidgets.QLabel(self.cardInfo_4)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        self.deadLine_4.setFont(font)
        self.deadLine_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.deadLine_4.setTextFormat(QtCore.Qt.AutoText)
        self.deadLine_4.setAlignment(QtCore.Qt.AlignCenter)
        self.deadLine_4.setObjectName("deadLine_4")
        self.verticalLayout_4.addWidget(self.deadLine_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.submitButton_4.setText(_translate("Form", "NULL"))
        self.ClassName_4.setText(_translate("Form", "课程名称"))
        self.className_4.setText(_translate("Form", "NULL"))
        self.DeadLine_4.setText(_translate("Form", "截止日期"))
        self.deadLine_4.setText(_translate("Form", "NULL"))

    def setTheText(self, className, deadLine, submit):
        self.deadLine_4.setText(deadLine)
        self.className_4.setText(className)
        self.submitButton_4.setText(submit)

    def setButton(self):
        self.submitButton_4.setStyleSheet("background-color: gray;")
        self.submitButton_4.setText("已提交")
        self.testCard_4.setStyleSheet("background-color: rgb(64, 128, 2);\n"
                                          "border-radius: 10px;")
        self.cardInfo_4.setStyleSheet("background-color: rgb(64, 128, 2);\n"
                                          "border-radius: 10px;\n"
                                          "color:white;")