# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 399)
        MainWindow.setMinimumSize(QtCore.QSize(640, 340))
        MainWindow.setMaximumSize(QtCore.QSize(640, 500))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"outline:none;\n"
"color:white;")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.topTitleBar = QtWidgets.QWidget(self.centralwidget)
        self.topTitleBar.setGeometry(QtCore.QRect(0, 0, 640, 56))
        self.topTitleBar.setStyleSheet("\n"
"border:none;\n"
"\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.697, y2:0, stop:0 rgba(230, 230, 230, 255), stop:1 rgba(204, 204, 204, 255));\n"
"")
        self.topTitleBar.setObjectName("topTitleBar")
        self.closeButton = QtWidgets.QPushButton(self.topTitleBar)
        self.closeButton.setGeometry(QtCore.QRect(8, 8, 14, 14))
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(9)
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet("QPushButton{\n"
"color : white;\n"
"border : none;\n"
"background-color : rgb(253, 102, 102);\n"
"border-radius:7px;\n"
"}\n"
"QPushButton:hover{\n"
"color: black;}")
        self.closeButton.setObjectName("closeButton")
        self.minimumButton = QtWidgets.QPushButton(self.topTitleBar)
        self.minimumButton.setGeometry(QtCore.QRect(30, 8, 14, 14))
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(9)
        self.minimumButton.setFont(font)
        self.minimumButton.setStyleSheet("QPushButton{\n"
"color : white;\n"
"border : none;\n"
"background-color : rgb(254, 204, 102);\n"
"border-radius:7px;}\n"
"QPushButton:hover{\n"
"color: black;}")
        self.minimumButton.setObjectName("minimumButton")
        self.maximumButton = QtWidgets.QPushButton(self.topTitleBar)
        self.maximumButton.setGeometry(QtCore.QRect(52, 8, 14, 14))
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(9)
        self.maximumButton.setFont(font)
        self.maximumButton.setStyleSheet("QPushButton{\n"
"color : white;\n"
"border : none;\n"
"background-color : rgb(103, 194, 83);\n"
"border-radius:7px;}\n"
"QPushButton:hover{\n"
"color: black;}")
        self.maximumButton.setObjectName("maximumButton")
        self.userLogoButton = QtWidgets.QPushButton(self.topTitleBar)
        self.userLogoButton.setGeometry(QtCore.QRect(554, 12, 32, 32))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        self.userLogoButton.setFont(font)
        self.userLogoButton.setStyleSheet("border-radius:16px;\n"
"background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(15, 128, 255), stop:1 rgb(0, 0, 255));\n"
"")
        self.userLogoButton.setObjectName("userLogoButton")
        self.settingButton = QtWidgets.QPushButton(self.topTitleBar)
        self.settingButton.setGeometry(QtCore.QRect(596, 12, 32, 32))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(23)
        self.settingButton.setFont(font)
        self.settingButton.setStyleSheet("border-radius:16px;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"color : black;\n"
"\n"
"")
        self.settingButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/filter_g.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingButton.setIcon(icon)
        self.settingButton.setIconSize(QtCore.QSize(24, 24))
        self.settingButton.setObjectName("settingButton")
        self.workButton = QtWidgets.QPushButton(self.topTitleBar)
        self.workButton.setGeometry(QtCore.QRect(252, 12, 32, 32))
        self.workButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.workButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.workButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/order_g.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icon/order_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.workButton.setIcon(icon1)
        self.workButton.setIconSize(QtCore.QSize(32, 32))
        self.workButton.setCheckable(False)
        self.workButton.setChecked(False)
        self.workButton.setAutoDefault(False)
        self.workButton.setDefault(False)
        self.workButton.setObjectName("workButton")
        self.messageButton = QtWidgets.QPushButton(self.topTitleBar)
        self.messageButton.setGeometry(QtCore.QRect(304, 12, 32, 32))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.messageButton.setFont(font)
        self.messageButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.messageButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/user_g.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.messageButton.setIcon(icon2)
        self.messageButton.setIconSize(QtCore.QSize(32, 32))
        self.messageButton.setCheckable(False)
        self.messageButton.setObjectName("messageButton")
        self.settingsButton = QtWidgets.QPushButton(self.topTitleBar)
        self.settingsButton.setGeometry(QtCore.QRect(356, 12, 32, 32))
        self.settingsButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.settingsButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/setting_g.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon3)
        self.settingsButton.setIconSize(QtCore.QSize(32, 32))
        self.settingsButton.setCheckable(False)
        self.settingsButton.setObjectName("settingsButton")
        self.thirdW = QtWidgets.QWidget(self.centralwidget)
        self.thirdW.setGeometry(QtCore.QRect(0, 56, 640, 270))
        self.thirdW.setObjectName("thirdW")
        self.label_6 = QtWidgets.QLabel(self.thirdW)
        self.label_6.setGeometry(QtCore.QRect(280, 120, 58, 16))
        self.label_6.setStyleSheet("color:black;")
        self.label_6.setObjectName("label_6")
        self.firstW = QtWidgets.QWidget(self.centralwidget)
        self.firstW.setEnabled(True)
        self.firstW.setGeometry(QtCore.QRect(0, 56, 640, 330))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        self.firstW.setFont(font)
        self.firstW.setObjectName("firstW")




        self.cardArea = QtWidgets.QScrollArea(self.firstW)
        self.cardArea.setGeometry(QtCore.QRect(0, 0, 640, 240))
        self.cardArea.setStyleSheet("border:none;")
        self.cardArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cardArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.cardArea.setWidgetResizable(True)
        self.cardArea.setObjectName("cardArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 640, 240))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(638, 220))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(0, 0, 640, 240))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setKerning(True)
        self.widget.setFont(font)
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setAutoFillBackground(False)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.testCard_1 = QtWidgets.QWidget(self.widget)
        self.testCard_1.setMinimumSize(QtCore.QSize(200, 200))
        self.testCard_1.setMaximumSize(QtCore.QSize(200, 200))
        self.testCard_1.setStyleSheet("background-color: rgb(15, 128, 255);\n"
"\n"
"border-radius: 10px;")
        self.testCard_1.setObjectName("testCard_1")
        self.submitButton = QtWidgets.QPushButton(self.testCard_1)
        self.submitButton.setGeometry(QtCore.QRect(52, 140, 96, 32))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        self.submitButton.setFont(font)
        self.submitButton.setStyleSheet("background-color: rgb(0, 204, 0);")
        self.submitButton.setObjectName("submitButton")
        self.cardInfo_1 = QtWidgets.QWidget(self.testCard_1)
        self.cardInfo_1.setGeometry(QtCore.QRect(0, 10, 200, 120))
        self.cardInfo_1.setStyleSheet("color:white;")
        self.cardInfo_1.setObjectName("cardInfo_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.cardInfo_1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ClassName = QtWidgets.QLabel(self.cardInfo_1)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(18)
        self.ClassName.setFont(font)
        self.ClassName.setAutoFillBackground(False)
        self.ClassName.setAlignment(QtCore.Qt.AlignCenter)
        self.ClassName.setWordWrap(False)
        self.ClassName.setObjectName("ClassName")
        self.verticalLayout.addWidget(self.ClassName)
        self.className = QtWidgets.QLabel(self.cardInfo_1)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        self.className.setFont(font)
        self.className.setAlignment(QtCore.Qt.AlignCenter)
        self.className.setObjectName("className")
        self.verticalLayout.addWidget(self.className)
        self.DeadLine = QtWidgets.QLabel(self.cardInfo_1)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(18)
        self.DeadLine.setFont(font)
        self.DeadLine.setAlignment(QtCore.Qt.AlignCenter)
        self.DeadLine.setObjectName("DeadLine")
        self.verticalLayout.addWidget(self.DeadLine)
        self.deadLine = QtWidgets.QLabel(self.cardInfo_1)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        self.deadLine.setFont(font)
        self.deadLine.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.deadLine.setTextFormat(QtCore.Qt.AutoText)
        self.deadLine.setAlignment(QtCore.Qt.AlignCenter)
        self.deadLine.setObjectName("deadLine")
        self.verticalLayout.addWidget(self.deadLine)
        self.horizontalLayout.addWidget(self.testCard_1)
        self.testCard_4 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testCard_4.sizePolicy().hasHeightForWidth())
        self.testCard_4.setSizePolicy(sizePolicy)
        self.testCard_4.setMinimumSize(QtCore.QSize(200, 200))
        self.testCard_4.setMaximumSize(QtCore.QSize(200, 200))
        self.testCard_4.setStyleSheet("background-color: rgb(64, 128, 2);\n"
"border-radius: 10px;")
        self.testCard_4.setObjectName("testCard_4")
        self.submitButton_4 = QtWidgets.QPushButton(self.testCard_4)
        self.submitButton_4.setEnabled(False)
        self.submitButton_4.setGeometry(QtCore.QRect(52, 140, 96, 32))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        self.submitButton_4.setFont(font)
        self.submitButton_4.setAcceptDrops(False)
        self.submitButton_4.setStyleSheet("QPushButton{\n"
"background-color: rgb(179, 179, 179);}\n"
"QPushButton:enabled{\n"
"background-color: rgb(0, 204, 0);}")
        self.submitButton_4.setAutoDefault(False)
        self.submitButton_4.setDefault(False)
        self.submitButton_4.setFlat(False)
        self.submitButton_4.setObjectName("submitButton_4")
        self.cardInfo_4 = QtWidgets.QWidget(self.testCard_4)
        self.cardInfo_4.setGeometry(QtCore.QRect(0, 10, 200, 120))
        self.cardInfo_4.setStyleSheet("color:white;")
        self.cardInfo_4.setObjectName("cardInfo_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.cardInfo_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ClassName_4 = QtWidgets.QLabel(self.cardInfo_4)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(18)
        self.ClassName_4.setFont(font)
        self.ClassName_4.setAutoFillBackground(False)
        self.ClassName_4.setAlignment(QtCore.Qt.AlignCenter)
        self.ClassName_4.setWordWrap(False)
        self.ClassName_4.setObjectName("ClassName_4")
        self.verticalLayout_4.addWidget(self.ClassName_4)
        self.className_4 = QtWidgets.QLabel(self.cardInfo_4)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        self.className_4.setFont(font)
        self.className_4.setAlignment(QtCore.Qt.AlignCenter)
        self.className_4.setObjectName("className_4")
        self.verticalLayout_4.addWidget(self.className_4)
        self.DeadLine_4 = QtWidgets.QLabel(self.cardInfo_4)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(18)
        self.DeadLine_4.setFont(font)
        self.DeadLine_4.setAlignment(QtCore.Qt.AlignCenter)
        self.DeadLine_4.setObjectName("DeadLine_4")
        self.verticalLayout_4.addWidget(self.DeadLine_4)
        self.deadLine_4 = QtWidgets.QLabel(self.cardInfo_4)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        self.deadLine_4.setFont(font)
        self.deadLine_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.deadLine_4.setTextFormat(QtCore.Qt.AutoText)
        self.deadLine_4.setAlignment(QtCore.Qt.AlignCenter)
        self.deadLine_4.setObjectName("deadLine_4")
        self.verticalLayout_4.addWidget(self.deadLine_4)
        self.horizontalLayout.addWidget(self.testCard_4)
        self.testCard_3 = QtWidgets.QWidget(self.widget)
        self.testCard_3.setMinimumSize(QtCore.QSize(200, 200))
        self.testCard_3.setMaximumSize(QtCore.QSize(200, 200))
        self.testCard_3.setStyleSheet("background-color: rgb(64, 128, 2);\n"
"border-radius: 10px;")
        self.testCard_3.setObjectName("testCard_3")
        self.submitButton_3 = QtWidgets.QPushButton(self.testCard_3)
        self.submitButton_3.setEnabled(False)
        self.submitButton_3.setGeometry(QtCore.QRect(52, 140, 96, 32))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        self.submitButton_3.setFont(font)
        self.submitButton_3.setAcceptDrops(False)
        self.submitButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(179, 179, 179);}\n"
"QPushButton:enabled{\n"
"background-color: rgb(0, 204, 0);}")
        self.submitButton_3.setAutoDefault(False)
        self.submitButton_3.setDefault(False)
        self.submitButton_3.setFlat(False)
        self.submitButton_3.setObjectName("submitButton_3")
        self.cardInfo_3 = QtWidgets.QWidget(self.testCard_3)
        self.cardInfo_3.setGeometry(QtCore.QRect(0, 10, 200, 120))
        self.cardInfo_3.setStyleSheet("color:white;")
        self.cardInfo_3.setObjectName("cardInfo_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cardInfo_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ClassName_3 = QtWidgets.QLabel(self.cardInfo_3)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(18)
        self.ClassName_3.setFont(font)
        self.ClassName_3.setAutoFillBackground(False)
        self.ClassName_3.setAlignment(QtCore.Qt.AlignCenter)
        self.ClassName_3.setWordWrap(False)
        self.ClassName_3.setObjectName("ClassName_3")
        self.verticalLayout_3.addWidget(self.ClassName_3)
        self.className_3 = QtWidgets.QLabel(self.cardInfo_3)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        self.className_3.setFont(font)
        self.className_3.setAlignment(QtCore.Qt.AlignCenter)
        self.className_3.setObjectName("className_3")
        self.verticalLayout_3.addWidget(self.className_3)
        self.DeadLine_3 = QtWidgets.QLabel(self.cardInfo_3)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(18)
        self.DeadLine_3.setFont(font)
        self.DeadLine_3.setAlignment(QtCore.Qt.AlignCenter)
        self.DeadLine_3.setObjectName("DeadLine_3")
        self.verticalLayout_3.addWidget(self.DeadLine_3)
        self.deadLine_3 = QtWidgets.QLabel(self.cardInfo_3)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        self.deadLine_3.setFont(font)
        self.deadLine_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.deadLine_3.setTextFormat(QtCore.Qt.AutoText)
        self.deadLine_3.setAlignment(QtCore.Qt.AlignCenter)
        self.deadLine_3.setObjectName("deadLine_3")
        self.verticalLayout_3.addWidget(self.deadLine_3)
        self.horizontalLayout.addWidget(self.testCard_3)
        self.cardArea.setWidget(self.scrollAreaWidgetContents)
        self.secondW = QtWidgets.QWidget(self.centralwidget)
        self.secondW.setGeometry(QtCore.QRect(0, 56, 640, 300))
        self.secondW.setStyleSheet("color : black;")
        self.secondW.setObjectName("secondW")
        self.userLogoButtonBig = QtWidgets.QPushButton(self.secondW)
        self.userLogoButtonBig.setGeometry(QtCore.QRect(50, 20, 96, 96))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(39)
        self.userLogoButtonBig.setFont(font)
        self.userLogoButtonBig.setStyleSheet("border-radius:48px;\n"
"background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(15, 128, 255), stop:1 rgb(0, 0, 255));\n"
"color:white;\n"
"")
        self.userLogoButtonBig.setObjectName("userLogoButtonBig")
        self.changeLogoColor = QtWidgets.QPushButton(self.secondW)
        self.changeLogoColor.setGeometry(QtCore.QRect(59, 126, 78, 13))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(11)
        font.setKerning(True)
        self.changeLogoColor.setFont(font)
        self.changeLogoColor.setStyleSheet("border:none;\n"
"background-color: rgb(179, 179, 179);\n"
"border-radius:6px;\n"
"color:rgb(76, 76, 76)")
        self.changeLogoColor.setObjectName("changeLogoColor")
        self.changePasswd = QtWidgets.QPushButton(self.secondW)
        self.changePasswd.setGeometry(QtCore.QRect(75, 150, 46, 13))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(11)
        self.changePasswd.setFont(font)
        self.changePasswd.setStyleSheet("border:none;\n"
"background-color: rgb(179, 179, 179);\n"
"border-radius:6px;\n"
"color:rgb(76, 76, 76)")
        self.changePasswd.setObjectName("changePasswd")
        self.userInfoDetail = QtWidgets.QWidget(self.secondW)
        self.userInfoDetail.setGeometry(QtCore.QRect(146, 20, 491, 251))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        self.userInfoDetail.setFont(font)
        self.userInfoDetail.setObjectName("userInfoDetail")
        self.myInfo = QtWidgets.QLabel(self.userInfoDetail)
        self.myInfo.setGeometry(QtCore.QRect(20, 0, 90, 20))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(20)
        self.myInfo.setFont(font)
        self.myInfo.setObjectName("myInfo")
        self.layoutWidget = QtWidgets.QWidget(self.userInfoDetail)
        self.layoutWidget.setGeometry(QtCore.QRect(92, 40, 254, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.userInfoLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.userInfoLayout.setContentsMargins(0, 0, 0, 0)
        self.userInfoLayout.setObjectName("userInfoLayout")
        self.name = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(30)
        self.name.setFont(font)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.userInfoLayout.addWidget(self.name)
        self.ID = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(30)
        self.ID.setFont(font)
        self.ID.setAlignment(QtCore.Qt.AlignCenter)
        self.ID.setObjectName("ID")
        self.userInfoLayout.addWidget(self.ID)
        self.class_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(30)
        self.class_2.setFont(font)
        self.class_2.setObjectName("class_2")
        self.userInfoLayout.addWidget(self.class_2)
        self.topTitleBar.raise_()
        self.thirdW.raise_()
        self.secondW.raise_()
        self.firstW.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.messageButton.clicked.connect(self.secondW.raise_)
        self.settingsButton.clicked.connect(self.thirdW.raise_)
        self.workButton.clicked.connect(self.firstW.raise_)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.closeButton.setText(_translate("MainWindow", "×"))
        self.minimumButton.setText(_translate("MainWindow", "-"))
        self.maximumButton.setText(_translate("MainWindow", "+"))
        self.userLogoButton.setText(_translate("MainWindow", "哲"))
        self.label_6.setText(_translate("MainWindow", "界面3"))
        self.submitButton.setText(_translate("MainWindow", "点击提交"))
        self.ClassName.setText(_translate("MainWindow", "课程名称"))
        self.className.setText(_translate("MainWindow", "C语言程序设计实验"))
        self.DeadLine.setText(_translate("MainWindow", "截止日期"))
        self.deadLine.setText(_translate("MainWindow", "2019年12月10日"))
        self.submitButton_4.setText(_translate("MainWindow", "已提交"))
        self.ClassName_4.setText(_translate("MainWindow", "课程名称"))
        self.className_4.setText(_translate("MainWindow", "Python程序设计实验"))
        self.DeadLine_4.setText(_translate("MainWindow", "截止日期"))
        self.deadLine_4.setText(_translate("MainWindow", "2019年11月10日"))
        self.submitButton_3.setText(_translate("MainWindow", "已提交"))
        self.ClassName_3.setText(_translate("MainWindow", "课程名称"))
        self.className_3.setText(_translate("MainWindow", "Python程序设计实验"))
        self.DeadLine_3.setText(_translate("MainWindow", "截止日期"))
        self.deadLine_3.setText(_translate("MainWindow", "2019年11月10日"))
        self.userLogoButtonBig.setText(_translate("MainWindow", "哲"))
        self.changeLogoColor.setText(_translate("MainWindow", "更改头像背景"))
        self.changePasswd.setText(_translate("MainWindow", "修改密码"))
        self.myInfo.setText(_translate("MainWindow", "我的信息:"))
        self.name.setText(_translate("MainWindow", "范润哲"))
        self.ID.setText(_translate("MainWindow", "170267"))
        self.class_2.setText(_translate("MainWindow", "信息与计算科学172"))
import mainWindowIcon_rc
